spring.application.name=airlinebooking

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/airline_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:2403cL003kiha}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:jnxdcdbxjhdb54144YTDBRCVNGHJ}
app.jwt.expiration-ms=86400000